# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainframe.ui'
#
# Created: Sun Jun 07 10:29:52 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.toolBox = QtGui.QToolBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBox.setObjectName("toolBox")
        self.page1 = QtGui.QWidget()
        self.page1.setGeometry(QtCore.QRect(0, 0, 256, 366))
        self.page1.setObjectName("page1")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.page1)
        self.verticalLayout_9.setSpacing(3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tree = QtGui.QTreeWidget(self.page1)
        self.tree.setObjectName("tree")
        self.verticalLayout_9.addWidget(self.tree)
        self.toolBox.addItem(self.page1, "")
        self.page2 = QtGui.QWidget()
        self.page2.setGeometry(QtCore.QRect(0, 0, 83, 71))
        self.page2.setObjectName("page2")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.page2)
        self.verticalLayout_10.setSpacing(3)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.db_tree = QtGui.QTreeWidget(self.page2)
        self.db_tree.setObjectName("db_tree")
        self.verticalLayout_10.addWidget(self.db_tree)
        self.toolBox.addItem(self.page2, "")
        self.page3 = QtGui.QWidget()
        self.page3.setGeometry(QtCore.QRect(0, 0, 83, 71))
        self.page3.setObjectName("page3")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.page3)
        self.verticalLayout_11.setSpacing(3)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.conf_tree = QtGui.QTreeWidget(self.page3)
        self.conf_tree.setObjectName("conf_tree")
        self.verticalLayout_11.addWidget(self.conf_tree)
        self.toolBox.addItem(self.page3, "")
        self.tabs = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs.sizePolicy().hasHeightForWidth())
        self.tabs.setSizePolicy(sizePolicy)
        self.tabs.setAcceptDrops(True)
        self.tabs.setObjectName("tabs")
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName("tab1")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text1 = QtGui.QTextEdit(self.tab1)
        self.text1.setObjectName("text1")
        self.verticalLayout.addWidget(self.text1)
        self.tabs.addTab(self.tab1, "")
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName("tab2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab2)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.text2 = QtGui.QTextEdit(self.tab2)
        self.text2.setObjectName("text2")
        self.verticalLayout_2.addWidget(self.text2)
        self.tabs.addTab(self.tab2, "")
        self.tab3 = QtGui.QWidget()
        self.tab3.setObjectName("tab3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab3)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.table3 = QtGui.QTableWidget(self.tab3)
        self.table3.setObjectName("table3")
        self.table3.setColumnCount(6)
        self.table3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table3.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table3.setHorizontalHeaderItem(5, item)
        self.verticalLayout_3.addWidget(self.table3)
        self.tabs.addTab(self.tab3, "")
        self.tab4 = QtGui.QWidget()
        self.tab4.setObjectName("tab4")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab4)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.table4 = QtGui.QTableWidget(self.tab4)
        self.table4.setObjectName("table4")
        self.table4.setColumnCount(8)
        self.table4.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table4.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table4.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table4.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table4.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table4.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table4.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.table4.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.table4.setHorizontalHeaderItem(7, item)
        self.verticalLayout_4.addWidget(self.table4)
        self.tabs.addTab(self.tab4, "")
        self.tab5 = QtGui.QWidget()
        self.tab5.setObjectName("tab5")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab5)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.table5 = QtGui.QTableWidget(self.tab5)
        self.table5.setObjectName("table5")
        self.table5.setColumnCount(2)
        self.table5.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table5.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table5.setHorizontalHeaderItem(1, item)
        self.verticalLayout_5.addWidget(self.table5)
        self.tabs.addTab(self.tab5, "")
        self.tab6 = QtGui.QWidget()
        self.tab6.setObjectName("tab6")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab6)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.table6 = QtGui.QTableWidget(self.tab6)
        self.table6.setObjectName("table6")
        self.table6.setColumnCount(7)
        self.table6.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table6.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table6.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table6.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table6.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table6.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table6.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.table6.setHorizontalHeaderItem(6, item)
        self.verticalLayout_6.addWidget(self.table6)
        self.tabs.addTab(self.tab6, "")
        self.tab7 = QtGui.QWidget()
        self.tab7.setObjectName("tab7")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab7)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.table7 = QtGui.QTableWidget(self.tab7)
        self.table7.setObjectName("table7")
        self.table7.setColumnCount(6)
        self.table7.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table7.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table7.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table7.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table7.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table7.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table7.setHorizontalHeaderItem(5, item)
        self.verticalLayout_7.addWidget(self.table7)
        self.tabs.addTab(self.tab7, "")
        self.tab8 = QtGui.QWidget()
        self.tab8.setObjectName("tab8")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab8)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.table8 = QtGui.QTableWidget(self.tab8)
        self.table8.setObjectName("table8")
        self.table8.setColumnCount(2)
        self.table8.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table8.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table8.setHorizontalHeaderItem(1, item)
        self.verticalLayout_8.addWidget(self.table8)
        self.tabs.addTab(self.tab8, "")
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSave = QtGui.QMenu(self.menubar)
        self.menuSave.setObjectName("menuSave")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionTaskDir = QtGui.QAction(MainWindow)
        self.actionTaskDir.setObjectName("actionTaskDir")
        self.actionTaskFile = QtGui.QAction(MainWindow)
        self.actionTaskFile.setObjectName("actionTaskFile")
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout_Qt = QtGui.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionSources = QtGui.QAction(MainWindow)
        self.actionSources.setObjectName("actionSources")
        self.actionObjects = QtGui.QAction(MainWindow)
        self.actionObjects.setObjectName("actionObjects")
        self.actionHandlers = QtGui.QAction(MainWindow)
        self.actionHandlers.setObjectName("actionHandlers")
        self.actionMethods = QtGui.QAction(MainWindow)
        self.actionMethods.setObjectName("actionMethods")
        self.actionDatabases = QtGui.QAction(MainWindow)
        self.actionDatabases.setObjectName("actionDatabases")
        self.actionAll = QtGui.QAction(MainWindow)
        self.actionAll.setObjectName("actionAll")
        self.menuFile.addAction(self.actionTaskDir)
        self.menuFile.addAction(self.actionTaskFile)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuSave.addAction(self.actionSources)
        self.menuSave.addAction(self.actionObjects)
        self.menuSave.addAction(self.actionHandlers)
        self.menuSave.addAction(self.actionMethods)
        self.menuSave.addAction(self.actionDatabases)
        self.menuSave.addSeparator()
        self.menuSave.addAction(self.actionAll)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSave.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.tabs.setCurrentIndex(2)
        QtCore.QObject.connect(self.actionTaskDir, QtCore.SIGNAL("triggered()"), MainWindow.OnTaskDir)
        QtCore.QObject.connect(self.actionTaskFile, QtCore.SIGNAL("triggered()"), MainWindow.OnTaskFile)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL("triggered()"), MainWindow.OnClose)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QObject.connect(self.actionAbout, QtCore.SIGNAL("triggered()"), MainWindow.OnAbout)
        QtCore.QObject.connect(self.actionAbout_Qt, QtCore.SIGNAL("triggered()"), MainWindow.OnAbout_Qt)
        QtCore.QObject.connect(self.toolBox, QtCore.SIGNAL("currentChanged(int)"), MainWindow.OnToolBoxChanged)
        QtCore.QObject.connect(self.tree, QtCore.SIGNAL("itemExpanded(QTreeWidgetItem*)"), MainWindow.OnTreeItemSelected)
        QtCore.QObject.connect(self.tree, QtCore.SIGNAL("currentItemChanged(QTreeWidgetItem*,QTreeWidgetItem*)"), MainWindow.OnTreeItemSelected)
        QtCore.QObject.connect(self.db_tree, QtCore.SIGNAL("currentItemChanged(QTreeWidgetItem*,QTreeWidgetItem*)"), MainWindow.OnTreeItemSelected)
        QtCore.QObject.connect(self.conf_tree, QtCore.SIGNAL("currentItemChanged(QTreeWidgetItem*,QTreeWidgetItem*)"), MainWindow.OnTreeItemSelected)
        QtCore.QObject.connect(self.tabs, QtCore.SIGNAL("currentChanged(int)"), MainWindow.OnTabChanged)
        QtCore.QObject.connect(self.menuSave, QtCore.SIGNAL("triggered(QAction*)"), MainWindow.OnSaveMenu)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.tree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page1), QtGui.QApplication.translate("MainWindow", "Task", None, QtGui.QApplication.UnicodeUTF8))
        self.db_tree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Table", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page2), QtGui.QApplication.translate("MainWindow", "Db", None, QtGui.QApplication.UnicodeUTF8))
        self.conf_tree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Key", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page3), QtGui.QApplication.translate("MainWindow", "Conf", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab1), QtGui.QApplication.translate("MainWindow", "Brief", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab2), QtGui.QApplication.translate("MainWindow", "Tracing", None, QtGui.QApplication.UnicodeUTF8))
        self.table3.setSortingEnabled(True)
        self.table3.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Source", None, QtGui.QApplication.UnicodeUTF8))
        self.table3.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Object", None, QtGui.QApplication.UnicodeUTF8))
        self.table3.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Handler", None, QtGui.QApplication.UnicodeUTF8))
        self.table3.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Method", None, QtGui.QApplication.UnicodeUTF8))
        self.table3.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Db", None, QtGui.QApplication.UnicodeUTF8))
        self.table3.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab3), QtGui.QApplication.translate("MainWindow", "Sources", None, QtGui.QApplication.UnicodeUTF8))
        self.table4.setSortingEnabled(True)
        self.table4.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.table4.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.table4.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Client", None, QtGui.QApplication.UnicodeUTF8))
        self.table4.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Contractor", None, QtGui.QApplication.UnicodeUTF8))
        self.table4.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Dept.", None, QtGui.QApplication.UnicodeUTF8))
        self.table4.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Started", None, QtGui.QApplication.UnicodeUTF8))
        self.table4.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Finished", None, QtGui.QApplication.UnicodeUTF8))
        self.table4.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab4), QtGui.QApplication.translate("MainWindow", "Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.table5.setSortingEnabled(True)
        self.table5.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.table5.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Revision", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab5), QtGui.QApplication.translate("MainWindow", "Handlers", None, QtGui.QApplication.UnicodeUTF8))
        self.table6.setSortingEnabled(True)
        self.table6.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.table6.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Revision", None, QtGui.QApplication.UnicodeUTF8))
        self.table6.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Dirs filter", None, QtGui.QApplication.UnicodeUTF8))
        self.table6.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Files filter", None, QtGui.QApplication.UnicodeUTF8))
        self.table6.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.table6.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Sheets filter", None, QtGui.QApplication.UnicodeUTF8))
        self.table6.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Sheet test", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab6), QtGui.QApplication.translate("MainWindow", "Methods", None, QtGui.QApplication.UnicodeUTF8))
        self.table7.setSortingEnabled(True)
        self.table7.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.table7.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.table7.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Db", None, QtGui.QApplication.UnicodeUTF8))
        self.table7.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Url", None, QtGui.QApplication.UnicodeUTF8))
        self.table7.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "User", None, QtGui.QApplication.UnicodeUTF8))
        self.table7.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab7), QtGui.QApplication.translate("MainWindow", "Databases", None, QtGui.QApplication.UnicodeUTF8))
        self.table8.setSortingEnabled(True)
        self.table8.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.table8.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Revision", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab8), QtGui.QApplication.translate("MainWindow", "Models", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSave.setTitle(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTaskDir.setText(QtGui.QApplication.translate("MainWindow", "Task Dir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTaskDir.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTaskFile.setText(QtGui.QApplication.translate("MainWindow", "Task File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTaskFile.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Qt.setText(QtGui.QApplication.translate("MainWindow", "About Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSources.setText(QtGui.QApplication.translate("MainWindow", "Sources", None, QtGui.QApplication.UnicodeUTF8))
        self.actionObjects.setText(QtGui.QApplication.translate("MainWindow", "Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHandlers.setText(QtGui.QApplication.translate("MainWindow", "Handlers", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMethods.setText(QtGui.QApplication.translate("MainWindow", "Methods", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDatabases.setText(QtGui.QApplication.translate("MainWindow", "Databases", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAll.setText(QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))

